app 102

diff --git a/.github/actions/app/action.yaml b/.github/actions/app/action.yaml
--- a/.github/actions/app/action.yaml
+++ b/.github/actions/app/action.yaml
@@ -111,14 +111,22 @@ runs:
           sudo mkdir -p logs
           sudo chown $USER:$USER logs
 
-          echo "Stopping any existing Gunicorn processes on port ${APP_PORT}"
-          PIDS=$(sudo netstat -tulnp | grep ":${APP_PORT}" | awk '{print $7}' | cut -d'/' -f1)
-
-          if [ -n "\$PIDS" ]; then
-            echo "Killing process IDs: \$PIDS"
-            sudo kill -9 $\PIDS
+          echo "${LOGS_SEPARATOR}"
+          echo "Stopping any existing Gunicorn processes on port ${APP_PORT}"     
+          PID=\$(sudo lsof -t -i :${APP_PORT})
+          # Check if PID is empty (i.e., no process found)
+          if [ -z "\$PID" ]; then
+            echo "No process found on port $PORT."
+          elif ps -p \$PID > /dev/null; then
+            # Kill the process
+            sudo kill -9 \$PID
+            if [ $? -eq 0 ]; then
+                echo "Killed process \$PID."
+            else
+                echo "Failed to kill process \$PID."
+            fi
           else
-            echo "No Gunicorn process found on port ${APP_PORT}."
+              echo "No process found with PID \$PID."
           fi
 
           echo "Starting Gunicorn"
