app 002

diff --git a/.github/actions/app/action.yaml b/.github/actions/app/action.yaml
--- a/.github/actions/app/action.yaml
+++ b/.github/actions/app/action.yaml
@@ -78,6 +78,8 @@ runs:
         rsync -avz -e "ssh -i private_key.pem -p ${TUNNEL} -o StrictHostKeyChecking=no" ./app/python/ ${USER}@localhost:/home/${USER}/my-app/
         ssh -i private_key.pem -p ${TUNNEL} -o StrictHostKeyChecking=no ${USER}@localhost << EOF | tee ${{ inputs.log_file }}  
 
+          set -euo pipefail  # Exit on error, undefined variables, or pipe failures
+          
           echo "${LOGS_SEPARATOR}"
           echo "Installing dependencies"
           cd /home/${USER}/my-app/
@@ -86,9 +88,10 @@ runs:
           pip install -r requirements.txt
 
           echo "${LOGS_SEPARATOR}"
-          echo "Maximing geolocation db"
-          curl -L -o GeoLite2-City.tar.gz \
-          "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz"  
+          echo "Maximind geolocation db"
+          wget "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$MAXIMIND_LICENSE_KEY&suffix=tar.gz" \ 
+          -O GeoLite2-City.tar.gz
+        
           tar -xvzf GeoLite2-City.tar.gz
           DB_DIR=\$(find . -type d -name 'GeoLite2-City_*' | head -n 1)
           cp "\$DB_DIR/GeoLite2-City.mmdb" ./GeoLite2-City.mmdb
