app 042

diff --git a/.github/actions/elk/action.yaml b/.github/actions/elk/action.yaml
--- a/.github/actions/elk/action.yaml
+++ b/.github/actions/elk/action.yaml
@@ -248,6 +248,10 @@ runs:
               }')
 
             echo "${LOGS_SEPARATOR}"
+            echo "Installing jq for parsing variable"
+            sudo apt-get install -y jq
+
+            echo "${LOGS_SEPARATOR}"
             echo "Extracting API key credentials"
             API_KEY_ID=\$(echo "$LOGSTASH_API_KEY_JASON" | jq -r '.id')
             API_KEY_SECRET=\$(echo "$LOGSTASH_API_KEY_JASON" | jq -r '.api_key')
@@ -322,6 +326,113 @@ runs:
             echo "restarting logstash"
             sudo systemctl restart logstash
           fi
+
+
+
+
+
+
+
+          echo "${LOGS_SEPARATOR}"
+          echo "Installing jq for parsing variable"
+          sudo apt-get install -y jq
+
+          echo "${LOGS_SEPARATOR}"
+          echo "checking cluster health to set logstash elasticsearch api"
+          echo decrypting elastic password
+          gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --decrypt elastic_password.txt.gpg > elastic_password.txt
+          ELASTIC_PASSWORD=\$(< elastic_password.txt)
+          echo "checkinh health"
+          MAX_RETRIES=12
+          RETRY_COUNT=0
+
+          until sudo curl -s -u elastic:\$ELASTIC_PASSWORD https://localhost:9200/_cluster/health \
+            --cacert /etc/elasticsearch/certs/http_ca.crt | grep -E -q '"status":"green"|"status":"yellow"'; do
+            if [ \$RETRY_COUNT -ge \$MAX_RETRIES ]; then
+              echo "Elasticsearch cluster failed to become healthy after \$((MAX_RETRIES * 5)) seconds."
+              exit 1
+            fi
+            echo "Waiting for Elasticsearch to become healthy... (\${RETRY_COUNT}/\${MAX_RETRIES})"
+            sleep 5
+            RETRY_COUNT=\$((RETRY_COUNT + 1))
+          done  
+          echo "Elasticsearch cluster is healthy!"
+
+          echo "${LOGS_SEPARATOR}"
+          echo "Generate api key for logstash kibana auth"
+          LOGSTASH_API_KEY_JASON=$(curl -s -X POST -u elastic:"\$ELASTIC_PASSWORD" \
+            -H "Content-Type: application/json" \
+            "https://localhost:"${ELASTICSEARCH_PORT}"/_security/api_key?pretty" \
+            -d '{
+              "name": "logstash-api-key",
+              "role_descriptors": {
+                "logstash_writer": {
+                  "cluster": ["monitor", "manage_index_templates"],
+                  "indices": [
+                    {
+                      "names": ["flask-logs-*"],
+                      "privileges": ["create_index", "write", "read"]
+                    }
+                  ]
+                }
+              }
+            }')
+
+          echo "${LOGS_SEPARATOR}"
+          echo "Installing jq for parsing variable"
+          sudo apt-get install -y jq
+
+          echo "${LOGS_SEPARATOR}"
+          echo "Extracting API key credentials"
+          API_KEY_ID=\$(echo "$LOGSTASH_API_KEY_JASON" | jq -r '.id')
+          API_KEY_SECRET=\$(echo "$LOGSTASH_API_KEY_JASON" | jq -r '.api_key')
+
+          echo "${LOGS_SEPARATOR}"
+          echo "gpg encryption of api keys"
+          echo "\$API_KEY_JSON" > logstash_api_key.json
+          echo "\$API_KEY_ID" > logstash_api_key_id.json
+          echo "\$API_KEY_SECRET" > logstash_api_key_secret.json
+          gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --symmetric --cipher-algo AES256 logstash_api_key.json
+          gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --symmetric --cipher-algo AES256 logstash_api_key_secret.json
+          gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --symmetric --cipher-algo AES256 logstash_api_key_id.json
+          rm logstash_api_key.json
+          rm logstash_api_key_id.json 
+          rm logstash_api_key_secret.json
+
+          echo "${LOGS_SEPARATOR}"
+          echo "logstash config file"
+          sudo tee /etc/logstash/conf.d/filebeat-to-es.conf > /dev/null << LOGSTASH_CONFIG
+            input {
+              beats {
+                port => ${LOGSTASH_PORT}
+              }
+            }
+
+            filter {
+              grok {
+                match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level}: %{GREEDYDATA:msg}" }
+              }
+              date {
+                match => ["timestamp", "ISO8601"]
+              }
+            }
+
+            output {
+              elasticsearch {
+                hosts => ["https://localhost:\${ELASTICSEARCH_PORT}"]
+                ssl => true
+                ssl_certificate_verification => true
+                cacert => "/etc/elasticsearch/certs/http_ca.crt"
+                index => "flask-logs-%{+YYYY.MM.dd}"
+                api_key => "\${API_KEY_ID}:\${API_KEY_SECRET}"
+                retry_initial_interval => 3
+                retry_max_interval => 60
+                retry_on_conflict => 3
+              }
+            }
+        LOGSTASH_CONFIG
+            echo "restarting logstash"
+            sudo systemctl restart logstash
 
 
           #checks
