app 075

diff --git a/.github/actions/elk/action.yaml b/.github/actions/elk/action.yaml
--- a/.github/actions/elk/action.yaml
+++ b/.github/actions/elk/action.yaml
@@ -126,6 +126,7 @@ runs:
           echo "${LOGS_SEPARATOR}"
           echo "restarting elasticsearch"
           sudo systemctl restart elasticsearch.service
+          sleep 60
 
 
           echo "Installing Kibana."
@@ -159,7 +160,7 @@ runs:
                 echo "Elasticsearch cluster failed to become healthy after \$((MAX_RETRIES * 5)) seconds."
                 echo "Attempting to restart Elasticsearch..."
                 sudo systemctl restart elasticsearch
-                sleep 30
+                sleep 60
                 RETRY_COUNT=0  # Reset count to re-check after restart
                 MAX_RETRIES=18  # Give fewer retries after restart
                 TOTAL_RETRIES=\$((TOTAL_RETRIES + 1))  # Increment total retry count
@@ -232,25 +233,32 @@ runs:
             gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --decrypt elastic_password.txt.gpg > elastic_password.txt
             ELASTIC_PASSWORD=\$(< elastic_password.txt)
             echo "checkinh health"
-            MAX_RETRIES=12
-            MAX_TOTAL_RETRIES=24
+            MAX_RETRIES=36
+            MAX_TOTAL_RETRIES=4
             RETRY_COUNT=0
+            TOTAL_RETRIES=0
 
-            until sudo curl -s -u elastic:\$ELASTIC_PASSWORD https://localhost:9200/_cluster/health | grep -E -q '"status":"green"|"status":"yellow"'; do
+            until sudo curl -s -u elastic:\$ELASTIC_PASSWORD https://localhost:9200/_cluster/health \
+            | grep -E -q '"status":"green"|"status":"yellow"'; do
               if [ \$RETRY_COUNT -ge \$MAX_RETRIES ]; then
+                if [ \$TOTAL_RETRIES -ge \$MAX_TOTAL_RETRIES ]; then
+                  echo "Maximum retry attempts reached. Exiting..."
+                  exit 1  # Exit after exceeding total retry limit
+                fi
                 echo "Elasticsearch cluster failed to become healthy after \$((MAX_RETRIES * 5)) seconds."
                 echo "Attempting to restart Elasticsearch..."
                 sudo systemctl restart elasticsearch
-
-                sleep 30
+                sleep 60
                 RETRY_COUNT=0  # Reset count to re-check after restart
-                MAX_RETRIES=6  # Give fewer retries after restart
+                MAX_RETRIES=18  # Give fewer retries after restart
+                TOTAL_RETRIES=\$((TOTAL_RETRIES + 1))  # Increment total retry count
               else
                 echo "Waiting for Elasticsearch to become healthy... (\${RETRY_COUNT}/\${MAX_RETRIES})"
                 sleep 5
                 RETRY_COUNT=\$((RETRY_COUNT + 1))
               fi
             done
+            echo "cluster healthy"
 
             echo "${LOGS_SEPARATOR}"
             echo "Generate api key for logstash kibana auth"
@@ -376,28 +384,33 @@ runs:
           gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --decrypt elastic_password.txt.gpg > elastic_password.txt
           ELASTIC_PASSWORD=\$(< elastic_password.txt)
           echo "checkinh health"
-          MAX_RETRIES=12
-          MAX_TOTAL_RETRIES=24
+          MAX_RETRIES=36
+          MAX_TOTAL_RETRIES=4
           RETRY_COUNT=0
+          TOTAL_RETRIES=0
 
           until sudo curl -s -u elastic:\$ELASTIC_PASSWORD https://localhost:9200/_cluster/health \
           | grep -E -q '"status":"green"|"status":"yellow"'; do
             if [ \$RETRY_COUNT -ge \$MAX_RETRIES ]; then
+              if [ \$TOTAL_RETRIES -ge \$MAX_TOTAL_RETRIES ]; then
+                echo "Maximum retry attempts reached. Exiting..."
+                exit 1  # Exit after exceeding total retry limit
+              fi
               echo "Elasticsearch cluster failed to become healthy after \$((MAX_RETRIES * 5)) seconds."
               echo "Attempting to restart Elasticsearch..."
               sudo systemctl restart elasticsearch
-
-              sleep 30
+              sleep 60
               RETRY_COUNT=0  # Reset count to re-check after restart
-              MAX_RETRIES=6  # Give fewer retries after restart
+              MAX_RETRIES=18  # Give fewer retries after restart
+              TOTAL_RETRIES=\$((TOTAL_RETRIES + 1))  # Increment total retry count
             else
               echo "Waiting for Elasticsearch to become healthy... (\${RETRY_COUNT}/\${MAX_RETRIES})"
               sleep 5
               RETRY_COUNT=\$((RETRY_COUNT + 1))
             fi
           done
-          rm elastic_password.txt
           echo "cluster healthy"
+          rm elastic_password.txt
           sudo systemctl restart logstash
           sudo systemctl restart kibana
 
