app 035

diff --git a/.github/actions/elk/action.yaml b/.github/actions/elk/action.yaml
--- a/.github/actions/elk/action.yaml
+++ b/.github/actions/elk/action.yaml
@@ -128,6 +128,35 @@ runs:
             sudo /bin/systemctl enable kibana.service
             sleep 10
             sudo systemctl start kibana.service
+
+            echo "${LOGS_SEPARATOR}"
+            echo "checking cluster health to set kibana token"
+            echo decrypting elastic password
+            gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --decrypt elastic_password.txt.gpg > elastic_password.txt
+            ELASTIC_PASSWORD=\$(< elastic_password.txt)
+            echo "checkinh health"
+            MAX_RETRIES=12
+            RETRY_COUNT=0
+
+            until sudo curl -s -u elastic:\$ELASTIC_PASSWORD https://localhost:9200/_cluster/health \
+              --cacert /etc/elasticsearch/certs/http_ca.crt | grep -E -q '"status":"green"|"status":"yellow"'; do
+              if [ \$RETRY_COUNT -ge \$MAX_RETRIES ]; then
+                echo "Elasticsearch cluster failed to become healthy after \$((MAX_RETRIES * 5)) seconds."
+                exit 1
+              fi
+              echo "Waiting for Elasticsearch to become healthy... (\${RETRY_COUNT}/\${MAX_RETRIES})"
+              sleep 5
+              RETRY_COUNT=\$((RETRY_COUNT + 1))
+            done  
+            echo "Elasticsearch cluster is healthy!"
+            rm elastic_password.txt
+            
+            echo "${LOGS_SEPARATOR}"
+            echo "setting enrolment token."
+            TOKEN=\$(sudo /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana)
+            sleep 20
+            echo "applying token to kibana setup."
+            sudo /usr/share/kibana/bin/kibana-setup --enrollment-token "\$TOKEN"
           else
             echo "Kibana already installed."
           fi
@@ -155,35 +184,6 @@ runs:
           sudo sed -i '/^#\?elasticsearch\.ssl\.certificateAuthorities:/d' /etc/kibana/kibana.yml && echo 'elasticsearch.ssl.certificateAuthorities: ["/etc/kibana/certs/http_ca.crt"]' | sudo tee -a /etc/kibana/kibana.yml > /dev/null
 
           echo "${LOGS_SEPARATOR}"
-          echo "checking cluster health to set kibana token"
-          echo decrypting elastic password
-          gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --decrypt elastic_password.txt.gpg > elastic_password.txt
-          ELASTIC_PASSWORD=\$(< elastic_password.txt)
-          echo "checkinh health"
-          MAX_RETRIES=12
-          RETRY_COUNT=0
-
-          until sudo curl -s -u elastic:\$ELASTIC_PASSWORD https://localhost:9200/_cluster/health \
-            --cacert /etc/elasticsearch/certs/http_ca.crt | grep -E -q '"status":"green"|"status":"yellow"'; do
-            if [ \$RETRY_COUNT -ge \$MAX_RETRIES ]; then
-              echo "Elasticsearch cluster failed to become healthy after \$((MAX_RETRIES * 5)) seconds."
-              exit 1
-            fi
-            echo "Waiting for Elasticsearch to become healthy... (\${RETRY_COUNT}/\${MAX_RETRIES})"
-            sleep 5
-            RETRY_COUNT=\$((RETRY_COUNT + 1))
-          done  
-          echo "Elasticsearch cluster is healthy!"
-          rm elastic_password.txt
-          
-          echo "${LOGS_SEPARATOR}"
-          echo "setting enrolment token."
-          TOKEN=\$(sudo /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana)
-          sleep 20
-          echo "applying token to kibana setup."
-          sudo /usr/share/kibana/bin/kibana-setup --enrollment-token "\$TOKEN"
-
-          echo "${LOGS_SEPARATOR}"
           echo "restarting kibana"
           sudo systemctl restart kibana.service
 
@@ -195,53 +195,75 @@ runs:
             sudo apt-get update -y && sudo apt-get install logstash
             sudo systemctl enable logstash.service  
             sudo systemctl start logstash.service
+
+            echo "${LOGS_SEPARATOR}"
+            echo "checking cluster health to set logstash elasticsearch api"
+            echo decrypting elastic password
+            gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --decrypt elastic_password.txt.gpg > elastic_password.txt
+            ELASTIC_PASSWORD=\$(< elastic_password.txt)
+            echo "checkinh health"
+            MAX_RETRIES=12
+            RETRY_COUNT=0
+
+            until sudo curl -s -u elastic:\$ELASTIC_PASSWORD https://localhost:9200/_cluster/health \
+              --cacert /etc/elasticsearch/certs/http_ca.crt | grep -E -q '"status":"green"|"status":"yellow"'; do
+              if [ \$RETRY_COUNT -ge \$MAX_RETRIES ]; then
+                echo "Elasticsearch cluster failed to become healthy after \$((MAX_RETRIES * 5)) seconds."
+                exit 1
+              fi
+              echo "Waiting for Elasticsearch to become healthy... (\${RETRY_COUNT}/\${MAX_RETRIES})"
+              sleep 5
+              RETRY_COUNT=\$((RETRY_COUNT + 1))
+            done  
+            echo "Elasticsearch cluster is healthy!"
+
+            echo "${LOGS_SEPARATOR}"
+            echo "Generate api key for logstash kibana auth"
+            API_KEY_JSON=$(curl -s -X POST -u elastic:"\$ELASTIC_PASSWORD" \
+              -H "Content-Type: application/json" \
+              "https://localhost:"${ELASTICSEARCH_PORT}"/_security/api_key?pretty" \
+              -d '{
+                "name": "logstash-api-key",
+                "role_descriptors": {
+                  "logstash_writer": {
+                    "cluster": ["monitor", "manage_index_templates"],
+                    "indices": [
+                      {
+                        "names": ["flask-logs-*"],
+                        "privileges": ["create_index", "write", "read"]
+                      }
+                    ]
+                  }
+                }
+              }')
+
+            echo "${LOGS_SEPARATOR}"
+            echo "Extracting API key credentials"
+            API_KEY_ID=$(echo "$API_KEY_JSON" | jq -r '.id')
+            API_KEY_SECRET=$(echo "$API_KEY_JSON" | jq -r '.api_key')
+
+            echo "${LOGS_SEPARATOR}"
+            echo "Creating Logstash keystore if not exists"
+            sudo mkdir -p /etc/logstash
+            sudo chown -R logstash:logstash /etc/logstash
+            sudo chmod 755 /etc/logstash
+            
+            LOGSTASH_KEYSTORE_PASS=\$(openssl rand -base64 32)
+            export LOGSTASH_KEYSTORE_PASS
+            echo y | sudo --preserve-env=LOGSTASH_KEYSTORE_PASS -u logstash \
+            /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash create
+
+            echo "${LOGS_SEPARATOR}"
+            echo "Storing key id and secret in Logstash keystore"
+            echo "$API_KEY_ID" | sudo /usr/share/logstash/bin/logstash-keystore add ES_API_KEY_ID --stdin
+            echo "$API_KEY_SECRET" | sudo /usr/share/logstash/bin/logstash-keystore add ES_API_KEY_SECRET --stdin
+            rm elastic_password.txt
           else
             echo "Logstash already installed."
           fi
 
           echo "${LOGS_SEPARATOR}"
           echo "setting logstash configs"
-          echo "Generate api key for logstash kibana auth"
-          API_KEY_JSON=$(curl -s -X POST -u elastic:"$ELASTIC_PASSWORD" \
-            -H "Content-Type: application/json" \
-            "https://localhost:"${ELASTICSEARCH_PORT}"/_security/api_key?pretty" \
-            -d '{
-              "name": "logstash-api-key",
-              "role_descriptors": {
-                "logstash_writer": {
-                  "cluster": ["monitor", "manage_index_templates"],
-                  "indices": [
-                    {
-                      "names": ["flask-logs-*"],
-                      "privileges": ["create_index", "write", "read"]
-                    }
-                  ]
-                }
-              }
-            }')
-
-          echo "${LOGS_SEPARATOR}"
-          echo "Extracting API key credentials"
-          API_KEY_ID=$(echo "$API_KEY_JSON" | jq -r '.id')
-          API_KEY_SECRET=$(echo "$API_KEY_JSON" | jq -r '.api_key')
-
-          echo "${LOGS_SEPARATOR}"
-          echo "Creating Logstash keystore if not exists"
-          sudo mkdir -p /etc/logstash
-          sudo chown -R logstash:logstash /etc/logstash
-          sudo chmod 755 /etc/logstash
-          
-          LOGSTASH_KEYSTORE_PASS=\$(openssl rand -base64 32)
-          export LOGSTASH_KEYSTORE_PASS
-          echo y | sudo --preserve-env=LOGSTASH_KEYSTORE_PASS -u logstash \
-          /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash create
-
-          echo "${LOGS_SEPARATOR}"
-          echo "Storing key id and secret in Logstash keystore"
-          echo "$API_KEY_ID" | sudo /usr/share/logstash/bin/logstash-keystore add ES_API_KEY_ID --stdin
-          echo "$API_KEY_SECRET" | sudo /usr/share/logstash/bin/logstash-keystore add ES_API_KEY_SECRET --stdin
-          
-          echo "${LOGS_SEPARATOR}"
           echo "adding elasticsearch port to logstash keystore"
           echo "${ELASTICSEARCH_PORT}" | sudo /usr/share/logstash/bin/logstash-keystore add ELASTICSEARCH_PORT --stdin
 
@@ -276,12 +298,9 @@ runs:
                 retry_on_conflict => 3
               }
             }
-
         LOGSTASH_CONFIG
-
           echo "restarting logstash"
           sudo systemctl restart logstash
-
 
           #checks
           sleep 20
