app0001

diff --git a/.github/workflows/app.yaml b/.github/workflows/app.yaml
--- a/.github/workflows/app.yaml
+++ b/.github/workflows/app.yaml
@@ -15,34 +15,115 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Setup SSH key
-        run: |
-          # Write the private key to a file
-          echo "${{ secrets.EC2_SSH_KEY }}" > github-ec2.pem
-          chmod 600 github-ec2.pem
-      - name: Connect to Bastion Host and Deploy
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ inputs.bastion_ip }}
-          port: ${{ secrets.SSH_PORT }}
-          username: ${{ secrets.EC2_USER }}
-          key: "github-ec2.pem"
-          script: |
-            # Connect to Private EC2 Instance
-            ssh -o StrictHostKeyChecking=no -i github-ec2.pem -p ${{ secrets.SSH_PORT }} ${{ secrets.EC2_USER }}@${{ inputs.ec2_ip }} <<EOF
-              # Your deployment commands here
-              mkdir -p /home/${{ secrets.EC2_USER }}/my-app/
-              cp -r ./app/python /home/${{ secrets.EC2_USER }}/my-app/
-              cd /home/${{ secrets.EC2_USER }}my-app/
-              pip install -r requirements.txt
-              gunicorn -w 4 -b 0.0.0.0:80 app:app &
+    - uses: actions/checkout@v2
+    - name: Setup SSH key & Connect to Bastion
+      env:
+        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
+        BASTION: ${{ inputs.bastion_ip }}
+        HOST: ${{ inputs.ec2_ip }}
+        USER: ${{ secrets.EC2_USER }}
+        PORT: ${{ secrets.SSH_PORT }}
+      run: |
+        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
+        ssh -o StrictHostKeyChecking=no -i github-ec2.pem -p ${PORT} ${USER}@${BASTION}
+        echo "Current directory: $(pwd)"
+        echo "Listing home directory:"
+        ls -la ~
+        ssh -o StrictHostKeyChecking=no -i github-ec2.pem -p ${PORT} ${USER}@${HOST}
+        mkdir -p /home/${{ secrets.EC2_USER }}/my-app/
+        cp -r ./app/python /home/${{ secrets.EC2_USER }}/my-app/
+        cd /home/${{ secrets.EC2_USER }}my-app/
+        pip install -r requirements.txt
+        gunicorn -w 4 -b 0.0.0.0:80 app:app &
+    
 
-            EOF
-      - name: Clean up private key
-        run: |
-          rm -f github-ec2.pem
+
+
+#         echo "Installing Node.js..."
+#         if ! command -v nvm &> /dev/null; then
+#           curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
+#           export NVM_DIR="$HOME/.nvm"
+#           [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+#         fi
+#         nvm install node
+
+#         echo "Installing PM2..."
+#         if ! command -v pm2 &> /dev/null; then
+#         npm install -g pm2
+#         fi
+
+#         REPO_URL="https://github.com/afkzoro/github-aws-ec2.git"
+#         BRANCH="main"
+#         REPO_DIR="$HOME/github-aws-ec2"
+
+#         if [ -d "$REPO_DIR/.git" ]; then
+#           cd "$REPO_DIR"
+#           git pull origin "$BRANCH"
+#         else
+#           git clone "$REPO_URL" "$REPO_DIR"
+#           cd "$REPO_DIR"
+#         fi
+
+#         cd "$REPO_DIR/simple-web-server"
+#         npm install
+
+#         cd ~/github-aws-ec2/simple-web-server
+#         git pull origin main
+#         npm install
+
+#         echo "Starting/restarting application..."
+#         pm2 restart server.js || pm2 start server.js
+#         '
+
+
+
+
+
+# name: Secure Deployment via Bastion
+
+# on:
+#   workflow_dispatch:
+#     inputs:
+#       bastion_ip:
+#         description: 'Bastion Public IP'
+#         required: true
+#         type: string
+#       ec2_ip:
+#         description: 'EC2 Private IP'
+#         required: true
+#         type: string
+# jobs:
+#   deploy:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+#       - name: Setup SSH key
+#         run: |
+#           # Write the private key to a file
+#           echo "${{ secrets.EC2_SSH_KEY }}" > github-ec2.pem
+#           chmod 600 github-ec2.pem
+#       - name: Connect to Bastion Host and Deploy
+#         uses: appleboy/ssh-action@master
+#         with:
+#           host: ${{ inputs.bastion_ip }}
+#           port: ${{ secrets.SSH_PORT }}
+#           username: ${{ secrets.EC2_USER }}
+#           key: github-ec2.pem
+#           script: |
+#             # Connect to Private EC2 Instance
+#             ssh -o StrictHostKeyChecking=no -i github-ec2.pem -p ${{ secrets.SSH_PORT }} ${{ secrets.EC2_USER }}@${{ inputs.ec2_ip }} <<EOF
+#               # Your deployment commands here
+#               mkdir -p /home/${{ secrets.EC2_USER }}/my-app/
+#               cp -r ./app/python /home/${{ secrets.EC2_USER }}/my-app/
+#               cd /home/${{ secrets.EC2_USER }}my-app/
+#               pip install -r requirements.txt
+#               gunicorn -w 4 -b 0.0.0.0:80 app:app &
+
+#             EOF
+#       - name: Clean up private key
+#         run: |
+#           rm -f github-ec2.pem
 
 
 # name: Secure Deployment via Bastion
