elk 068

diff --git a/.github/workflows/ochestrator.yaml b/.github/workflows/ochestrator.yaml
--- a/.github/workflows/ochestrator.yaml
+++ b/.github/workflows/ochestrator.yaml
@@ -60,166 +60,166 @@ jobs:
           name: terraform-outputs
           path: infra/aws/outputs.json
 
-  # scan:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     # 1. Checkout Code from GitHub
-  #     - name: Checkout Code
-  #       uses: actions/checkout@v2
+  scan:
+    runs-on: ubuntu-latest
+    steps:
+      # 1. Checkout Code from GitHub
+      - name: Checkout Code
+        uses: actions/checkout@v2
 
-  #     # 2. Set up Python environment and install dependencies
-  #     - name: Set up Python 3.x
-  #       uses: actions/setup-python@v2
-  #       with:
-  #         python-version: '3.10'
+      # 2. Set up Python environment and install dependencies
+      - name: Set up Python 3.x
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
 
-  #     - name: Install dependencies
-  #       run: |
-  #         python -m pip install --upgrade pip
-  #         pip install -r ./app/python/requirements.txt
-  #         pip install bandit safety
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r ./app/python/requirements.txt
+          pip install bandit safety
 
-  #     # 3. Run Bandit scan (Python code security scanner)
-  #     - name: Run Bandit Scan
-  #       run: |
-  #         pip install bandit
-  #         bandit -r ./app/python -f json -o app/python/bandit-report.json || exit 1
+      # 3. Run Bandit scan (Python code security scanner)
+      - name: Run Bandit Scan
+        run: |
+          pip install bandit
+          bandit -r ./app/python -f json -o app/python/bandit-report.json || exit 1
 
-  #     # 4. Run Safety scan (Dependency vulnerability scanner)
-  #     - name: Run Safety Scan
-  #       run: |
-  #         pip install safety
-  #         safety check -r app/python/requirements.txt --policy-file app/python/.safety.yaml --output json > app/python/safety-report.json || exit 1
+      # 4. Run Safety scan (Dependency vulnerability scanner)
+      - name: Run Safety Scan
+        run: |
+          pip install safety
+          safety check -r app/python/requirements.txt --policy-file app/python/.safety.yaml --output json > app/python/safety-report.json || exit 1
 
-  #     # 5. Upload the reports for later review
-  #     - name: Upload Bandit Report
-  #       if: always()  # Always upload, even if workflow fails
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: bandit-report
-  #         path: ./app/python/bandit-report.json
+      # 5. Upload the reports for later review
+      - name: Upload Bandit Report
+        if: always()  # Always upload, even if workflow fails
+        uses: actions/upload-artifact@v4
+        with:
+          name: bandit-report
+          path: ./app/python/bandit-report.json
 
-  #     - name: Upload Safety Report
-  #       if: always()  # Always upload, even if workflow fails
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: safety-report
-  #         path: ./app/python/safety-report.json 
+      - name: Upload Safety Report
+        if: always()  # Always upload, even if workflow fails
+        uses: actions/upload-artifact@v4
+        with:
+          name: safety-report
+          path: ./app/python/safety-report.json 
 
-  # build:
-  #   needs: scan # Ensure deploy only happens after the scan job
-  #   if: success() 
-  #   runs-on: ubuntu-latest
-  #   steps:
+  build:
+    needs: scan # Ensure deploy only happens after the scan job
+    if: success() 
+    runs-on: ubuntu-latest
+    steps:
     
-  #   # Checkout code from the repository
-  #   - name: Checkout code
-  #     uses: actions/checkout@v2
+    # Checkout code from the repository
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-  #   # Set up Docker Buildx (required for multi-platform builds)
-  #   - name: Set up Docker Buildx
-  #     uses: docker/setup-buildx-action@v2
+    # Set up Docker Buildx (required for multi-platform builds)
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v2
 
-  #   # Set up Docker
-  #   - name: Set up Docker
-  #     uses: docker/setup-qemu-action@v2
+    # Set up Docker
+    - name: Set up Docker
+      uses: docker/setup-qemu-action@v2
 
-  #   # Build the Docker image
-  #   - name: Build Docker image
-  #     run: |
-  #       docker build -t michaelkedey/jomacsdevsecops:latest -f app/containerization/Dockerfile app/python/
+    # Build the Docker image
+    - name: Build Docker image
+      run: |
+        docker build -t michaelkedey/jomacsdevsecops:latest -f app/containerization/Dockerfile app/python/
 
-  #   # Install Trivy
-  #   - name: Install Trivy
-  #     run: |
-  #       curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.40.0/trivy_0.40.0_Linux-64bit.deb -o trivy.deb
-  #       sudo dpkg -i trivy.deb
+    # Install Trivy
+    - name: Install Trivy
+      run: |
+        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.40.0/trivy_0.40.0_Linux-64bit.deb -o trivy.deb
+        sudo dpkg -i trivy.deb
 
-  #   # Scan the Docker image for vulnerabilities using Trivy
-  #   - name: Scan Docker image for vulnerabilities
-  #     id: trivy_scan
-  #     run: |
-  #       mkdir -p trivy-reports
-  #       trivy image --no-progress --severity HIGH,CRITICAL --format json --output trivy-reports/scan-report.json michaelkedey/jomacsdevsecops:latest
+    # Scan the Docker image for vulnerabilities using Trivy
+    - name: Scan Docker image for vulnerabilities
+      id: trivy_scan
+      run: |
+        mkdir -p trivy-reports
+        trivy image --no-progress --severity HIGH,CRITICAL --format json --output trivy-reports/scan-report.json michaelkedey/jomacsdevsecops:latest
 
-  #   # Upload the Trivy scan report as an artifact (so you can download it later)
-  #   - name: Upload Trivy scan report
-  #     if: always()
-  #     uses: actions/upload-artifact@v4
-  #     with:
-  #       name: trivy-scan-report
-  #       path: trivy-reports/scan-report.json
+    # Upload the Trivy scan report as an artifact (so you can download it later)
+    - name: Upload Trivy scan report
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: trivy-scan-report
+        path: trivy-reports/scan-report.json
     
-  #   # If no vulnerabilities with high severity are found, push to Docker Hub
-  #   - name: Push Docker image to Docker Hub
-  #     if: ${{ success() }}
-  #     env:
-  #       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-  #       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-  #     run: |
-  #       echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-  #       docker push michaelkedey/jomacsdevsecops:latest
+    # If no vulnerabilities with high severity are found, push to Docker Hub
+    - name: Push Docker image to Docker Hub
+      if: ${{ success() }}
+      env:
+        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      run: |
+        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
+        docker push michaelkedey/jomacsdevsecops:latest
 
-  # deploy-app:
-  #   needs: [terraform, scan] # Ensure deploy only happens after the scan job
-  #   if: success()  # Only run if the scan job succeeds
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     # 1. Checkout Code from GitHub
-  #     - name: Checkout Code
-  #       uses: actions/checkout@v2    
-  #     # 6. Set up SSH key and establish SSH Tunnel
-  #     - name: Set up SSH tunnel and deploy code
-  #       env:
-  #         PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
-  #         BASTION: ${{ needs.terraform.outputs.bastion_ip }}
-  #         HOST: ${{ needs.terraform.outputs.ec2_ip }}
-  #         USER: ${{ secrets.EC2_USER }}
-  #         PORT: ${{ secrets.SSH_PORT }}
-  #         TUNNEL: ${{ secrets.SSH_TUNNEL_PORT }}
+  deploy-app:
+    needs: [terraform, scan] # Ensure deploy only happens after the scan job
+    if: success()  # Only run if the scan job succeeds
+    runs-on: ubuntu-latest
+    steps:
+      # 1. Checkout Code from GitHub
+      - name: Checkout Code
+        uses: actions/checkout@v2    
+      # 6. Set up SSH key and establish SSH Tunnel
+      - name: Set up SSH tunnel and deploy code
+        env:
+          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
+          BASTION: ${{ needs.terraform.outputs.bastion_ip }}
+          HOST: ${{ needs.terraform.outputs.ec2_ip }}
+          USER: ${{ secrets.EC2_USER }}
+          PORT: ${{ secrets.SSH_PORT }}
+          TUNNEL: ${{ secrets.SSH_TUNNEL_PORT }}
 
-  #       run: |
-  #         echo "waiting for instances to be ready"
-  #         sleep 90
+        run: |
+          echo "waiting for instances to be ready"
+          sleep 90
 
-  #         echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
+          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
           
-  #         # Establish the SSH tunnel from GitHub Actions to the target EC2 instance
-  #         # This command forwards the local port ${TUNNEL} to the target EC2 instance's SSH (port 22)
-  #         ssh -i private_key.pem -o StrictHostKeyChecking=no -tt -L ${TUNNEL}:${HOST}:${PORT} -p ${PORT} ${USER}@${BASTION} -N -f
-  #     # 7. copy code and deploy 
-  #     - name: Deploy app and start Gunicorn
-  #       env:
-  #         USER: ${{ secrets.EC2_USER }}
-  #         TUNNEL: ${{ secrets.SSH_TUNNEL_PORT }}
-  #         HOST: ${{ needs.terraform.outputs.ec2_ip }}
-  #       run: |
-  #         rsync -avz -e "ssh -i private_key.pem -p ${TUNNEL} -o StrictHostKeyChecking=no" ./app/python/ ${USER}@localhost:/home/${USER}/my-app/
+          # Establish the SSH tunnel from GitHub Actions to the target EC2 instance
+          # This command forwards the local port ${TUNNEL} to the target EC2 instance's SSH (port 22)
+          ssh -i private_key.pem -o StrictHostKeyChecking=no -tt -L ${TUNNEL}:${HOST}:${PORT} -p ${PORT} ${USER}@${BASTION} -N -f
+      # 7. copy code and deploy 
+      - name: Deploy app and start Gunicorn
+        env:
+          USER: ${{ secrets.EC2_USER }}
+          TUNNEL: ${{ secrets.SSH_TUNNEL_PORT }}
+          HOST: ${{ needs.terraform.outputs.ec2_ip }}
+        run: |
+          rsync -avz -e "ssh -i private_key.pem -p ${TUNNEL} -o StrictHostKeyChecking=no" ./app/python/ ${USER}@localhost:/home/${USER}/my-app/
           
-  #         # SSH into the EC2 instance and install dependencies and start Gunicorn
-  #         ssh -i private_key.pem -p ${TUNNEL} -o StrictHostKeyChecking=no ${USER}@localhost << 'EOF'
-  #           # Install dependencies
-  #           cd /home/${USER}/my-app/
-  #           sudo apt-get update -y -y && sudo apt-get upgrade -y
-  #           sudo apt-get install python3-pip -y
-  #           sudo apt-get install gunicorn -y
-  #           sudo apt-get install python3-flask -y
-  #           pip install -r requirements.txt
-  #           # Start Gunicorn
-  #           sudo nohup gunicorn -w 4 -b 0.0.0.0:80 app:app > gunicorn.log 2>&1 &
-  #           echo "gunicorn log"
-  #           sudo cat gunicorn.log
-  #         EOF
-  #         # 8. Clean-up tunnel
-  #     - name: Cleanup SSH Tunnel
-  #       if: always()  # Runs even if previous steps fail
-  #       run: |
-  #         # Kill tunnel process using port ${TUNNEL}
-  #         pkill -f "ssh.*${TUNNEL}:.*${{ inputs.ec2_ip }}"
-  #         echo "SSH tunnel terminated"
+          # SSH into the EC2 instance and install dependencies and start Gunicorn
+          ssh -i private_key.pem -p ${TUNNEL} -o StrictHostKeyChecking=no ${USER}@localhost << 'EOF'
+            # Install dependencies
+            cd /home/${USER}/my-app/
+            sudo apt-get update -y -y && sudo apt-get upgrade -y
+            sudo apt-get install python3-pip -y
+            sudo apt-get install gunicorn -y
+            sudo apt-get install python3-flask -y
+            pip install -r requirements.txt
+            # Start Gunicorn
+            sudo nohup gunicorn -w 4 -b 0.0.0.0:80 app:app > gunicorn.log 2>&1 &
+            echo "gunicorn log"
+            sudo cat gunicorn.log
+          EOF
+          # 8. Clean-up tunnel
+      - name: Cleanup SSH Tunnel
+        if: always()  # Runs even if previous steps fail
+        run: |
+          # Kill tunnel process using port ${TUNNEL}
+          pkill -f "ssh.*${TUNNEL}:.*${{ inputs.ec2_ip }}"
+          echo "SSH tunnel terminated"
 
   deploy-elk:
-    needs: terraform  # Ensure deploy only happens after the scan job
+    needs: [ terraform, deploy-app ]  # Ensure deploy only happens after the scan job
     if: success()  # Only run if the app deploy job succeeds
     runs-on: ubuntu-latest
     steps:
